# 数据容器文件

import scrapy

class SpiderItem(scrapy.Item):
    pass

class EshianyycfItem(scrapy.Item):
    # 中文名
    cname = scrapy.Field()
    # 英文名
    ename = scrapy.Field()
    # 食品分类
    spfenlei = scrapy.Field()
    # 可食部%
    keshibu = scrapy.Field()
    # 来源
    laiyuan = scrapy.Field()
    # 产地
    chandi = scrapy.Field()
    # 能量(千焦)
    nengliang = scrapy.Field()
    # 蛋白质(克)
    danbaizhi = scrapy.Field()
    # 脂肪(克)
    zhifang = scrapy.Field()
    # 饱和脂肪酸(克)
    baohezhifang = scrapy.Field()
    # 反式脂肪酸(克)
    fanshizfs = scrapy.Field()
    # 单不饱和脂肪酸(克)
    dbbhzfs = scrapy.Field()
    # 多不饱和脂肪酸(克)
    duobbhzfs = scrapy.Field()
    # 胆固醇(毫克)
    dangc = scrapy.Field()
    # 碳水化合物(克)
    tshhw = scrapy.Field()
    # 糖(克)
    tang = scrapy.Field()
    # 乳糖(克)
    rutang = scrapy.Field()
    # 膳食纤维(克)
    sanshiqw = scrapy.Field()
    # 可溶性膳食纤维(克)
    kesxssqw = scrapy.Field()
    # 不溶性膳食纤维(克)
    bsxssqw = scrapy.Field()
    # 钠(毫克)
    jinshuna = scrapy.Field()
    # 维生素A(微克视黄醇当量)
    weishengshua = scrapy.Field()
    # 维生素D(微克)
    weishengshud = scrapy.Field()
    # 维生素E(毫克α-生育酚当量)
    weishengshue = scrapy.Field()
    # 维生素K(微克)
    weishengshuk = scrapy.Field()
    # 维生素B1（硫胺素）(毫克)
    weishengshub1 = scrapy.Field()
    # 维生素B2（核黄素）(毫克)
    weishengshub2 = scrapy.Field()
    # 维生素B6(毫克)
    weishengshub6 = scrapy.Field()
    # 维生素B12(微克)
    weishengshub12 = scrapy.Field()
    # 维生素C（抗坏血酸）(毫克)
    weishengshuc = scrapy.Field()
    # 烟酸（烟酰胺）(毫克)
    yanshuan = scrapy.Field()
    # 叶酸(微克叶酸当量)
    yeshuan = scrapy.Field()
    # 泛酸(毫克)
    fanshuan = scrapy.Field()
    # 生物素(微克)
    shenwushu = scrapy.Field()
    # 胆碱(毫克)
    danjian = scrapy.Field()
    # 磷(毫克)
    jinshulin = scrapy.Field()
    # 钾(毫克)
    jinshujia = scrapy.Field()
    # 镁(毫克)
    jinshumei = scrapy.Field()
    # 钙(毫克)
    jinshugai = scrapy.Field()
    # 铁(毫克)
    jinshutie = scrapy.Field()
    # 锌(毫克)
    jinshuxin = scrapy.Field()
    # 碘(微克)
    jinshudian = scrapy.Field()
    # 硒(微克)
    jinshudxi = scrapy.Field()
    # 铜(毫克)
    jinshutong = scrapy.Field()
    # 氟(毫克)
    jinshufu = scrapy.Field()
    # 锰(毫克)
    jinshumeng = scrapy.Field()
    # δ-E(毫克)
    deltae = scrapy.Field()
    # (β-γ)-E(毫克)
    beitae = scrapy.Field()
    # α-E(毫克)
    aerfae = scrapy.Field()
    # 胡萝卜素(微克)
    hulubo = scrapy.Field()
    # 脂肪酸（总）(克)
    zhifansz = scrapy.Field()
    # 灰分(克)
    huifen = scrapy.Field()
    # 水分(克)
    shuifen = scrapy.Field()
    # 能量(千卡)
    nengliangqk = scrapy.Field()
    # 详情链接
    xqurl = scrapy.Field()

